### ISSUE TITLE
Missing FLAG errror when building with clang

### ISSUE THREAD

**Issue by Luthaf** [MikeHeiber/Excimontec#107]
This is part of the JOSS review: https://github.com/openjournals/joss-reviews/issues/2307

I tried to build Excimontec using clang as the C++ compiler, which failed to compile since there is no `FLAGS` defined in the makefile for this compiler. Strangely, the condition trying to catch this 

```makefile
ifndef FLAGS
	$(error Valid compiler not detected.)
endif
```

did not catch anything, and instead the compilation failed due to C++11 specific constructs without `-std=c++11`. It looks like this code is not serving its intended purpose as far as I can understand it.

----

As a side note, using the same flags as GCC with clang makes the code compile fine and the tests pass on macOS, so I think support for clang is only a matter of detecting it.

**Comment by Luthaf** [comment]
I still have an error while building the code on the `joss-paper-update` branch because KMC_Lattice Makefile is not updated to the new compiler detection. If I copy/paste the corresponding code in the `KMC_Lattice/makefile` it works fine.

**Comment by MikeHeiber** [comment]
@Luthaf The current version on the `joss-paper-update` branch should work.  It's currently working with clang++ on Ubuntu in the TravisCI tests.  Make sure you are updating the submodule using `git checkout --recurse-submodules`.

**Comment by Luthaf** [comment]
I forgot to update the submodule, that's working fine now! Thanks for taking the time to do this
