### ISSUE TITLE
Is there documentation for simulation input? 

### ISSUE THREAD

**Issue by Luthaf** [MikeHeiber/Excimontec#109]
Looks like the input format is similar to the `parameters_default.txt` file at the root; but I could not find documentation for all parameters or this file format in the user manual. The part of documentation I found to be related to this is section I `Input Physical Parameter List`. Did I missed something?

Regarding the file format, what I mean is what's the syntax used here: is `//Enable_FRM` a comment? And `## Kinetic Monte Carlo Algorithm Parameters` a header? 

Also, `parameters_default.txt` seems to contain more sections than documented in `Input Physical Parameter List`.

**Comment by Luthaf** [comment]
Cross-linking this issue to https://github.com/openjournals/joss-reviews/issues/2307

**Comment by MikeHeiber** [comment]
I am currently updating the User Manual to address this issue.

**Comment by Luthaf** [comment]
The manual in `joss-paper-update` branch is already an improvement, and should be enough for the paper itself 😃 

I think it could be improved further by separating more the mathematical method descriptions and input file reference (LAMMPS documentation is a pretty good example of this: e.g. https://lammps.sandia.gov/doc/pair_lj_cut_coul.html). This allow "power-users" to quickly search for syntax & specific parameters documentation instead of looking though the full manual.

Additionally, I think that defining and documenting the formal structure of the input file (e.g. https://lammps.sandia.gov/doc/Commands_parse.html) would be very beneficial to Excimontec in the long run.
