### ISSUE TITLE
Contributor guidelines

### ISSUE THREAD

**Issue by MikeHeiber** [MikeHeiber/Excimontec#15]
Add a document with guidelines for how other developers can contribute to the project, including coding style, workflow details, and testing requirements.

- Requesting features and reporting bugs
- Making Tutorials
- Forks and feature branches
- Code testing
- Pull requests
- Standards and code review

**Comment by JoshuaSBrown** [comment]
Do you already have a branch open for this? We could borrow ideas from what is in the VOTCA repo they have a good initial set of rules.

**Comment by MikeHeiber** [comment]
I have not yet started working on this.  If you have some ideas, start a contributor-guidelines feature branch.
