### ISSUE TITLE
Add clang formatter 

### ISSUE THREAD

**Issue by JoshuaSBrown** [MikeHeiber/Excimontec#22]
This will help keep the style of the source files consistent to add clarity and readability.

**Comment by MikeHeiber** [comment]
@JoshuaSBrown Can you explain how this will work?  When is the code formatted?  Does it format code when people do commits or pull requests?  How can we format the existing code?  Do we need hooks to trigger the code formatting?  I'd like a clear understanding of how it works and an example of how it is formatting the code before it's implemented into the repo.

**Comment by JoshuaSBrown** [comment]
My apologies didn't really explain this one well. The .clang-format file is used on a case by case basis. At least that's how we use it in VOTCA, it is not strictly enforced. As long as the .clang-format file exists in a folder higher in the directory structure it will be called when you execute the following command. 

```
clang-format -style=file temp.cpp
```
So in this example the argument `-style=file` indicates to clang that it should look for the .clang-format file somewhere in the directory structure. It will then format the temp.cpp file according to the guidelines in the file and print it to the screen. If you use the `-i` flag as well it will apply the format directly to the file and change it, as opposed to simply printing to the screen. 

I'm not sure I would automate a call to it, as there may be some cases where you have formatted the code in a clearer fashion. I would recommend using it as a tool during the early stage of development. Does that clarify it?

**Comment by JoshuaSBrown** [comment]
In later versions there is an option to make the clang-format command ignore certain sections of code that have been formatted more cleanly. So it could be automated effectively if this is the case but it is your call.
