### ISSUE TITLE
Allow System Tests to run even if slurm is not found

### ISSUE THREAD

**Issue by JoshuaSBrown** [MikeHeiber/Excimontec#38]
Currently if slurm is not installed system_test1.sh will not run.

**Comment by JoshuaSBrown** [comment]
@MikeHeiber before I start playing around with this was this actually fully implemented? I get the feeling that it was not quite finished. If you are still working on this I will just wait.

**Comment by MikeHeiber** [comment]
There is not currently a system_test1.sh in the repo.  If you think we should add system tests of a certain type, make an issue and we can discuss what types of tests seem best to run.  Then, we can create a feature branch where we add it.
