### ISSUE TITLE
Create File for Controlling Version

### ISSUE THREAD

**Issue by JoshuaSBrown** [MikeHeiber/Excimontec#39]
Ideally this class or file would control all functionality associated with versioning. E.g. 

Version.h
```
namespace Excimontec {
  class Version {
    private:
      int major_ = 1;
      int minor_ = 0;
      int bug_release_ = 5;
      std::string release_type_ = "beta";
    public:
      const int getMajor(){return major_;}
      const int getMinor(){return minor_;}
      const int getBugRelease(){return bug_release_;}
      const std::string getReleaseType(){return release_type_;}
      const std::string getVersion(){
        return "v"+to_string(major)+"."+to_string(minor)+"-"
          release_type_+"."+to_string(bug_release_);
      }
  } version;
}
```
Some thing like this it would also be useful if the class also had functionality for dealing with translating a string into a version. For instance if you want to check if a file output by the OSC_Sim code is still compatible with the current version. This will also make it easier to compare the releases if you easily grab the integer values of the major and minor releases. 

Also when implementing cmake the versioning can then also be controlled easily using cmake variables. 

Version.h.in
```
namespace Excimontec {
  class Version {
    private:
      int major_ = @MAJOR@;
      int minor_ = @MINOR@;
      int bug_release_ = @BUG_RELEASE@;
      std::string release_type_ = @RELEASE_TYPE@;
    public:
      const int getMajor(){return major_;}
      const int getMinor(){return minor_;}
      const int getBugRelease(){return bug_release_;}
      const std::string getReleaseType(){return release_type_;}
      const std::string getVersion(){
        return "v"+to_string(major)+"."+to_string(minor)+"-"
          release_type_+"."+to_string(bug_release_);
      }
  } version;
}
```

You could even overload the < and > to easily compare if a version is newer.

**Comment by JoshuaSBrown** [comment]
Here is the branch:
https://github.com/MikeHeiber/Excimontec/tree/enhancement-version

**Comment by MikeHeiber** [comment]
This feature is now implemented in the KMC_Lattice submodule.
