### ISSUE TITLE
Import Site Energy Functionality from .txt file 

### ISSUE THREAD

**Issue by JoshuaSBrown** [MikeHeiber/Excimontec#8]
Functionality needs to be added to be able to import custom energy landscapes to run KMC on. This will be done by loading files in a similar manner to the topology.txt files.

**Comment by MikeHeiber** [comment]
I have assigned this as a feature that I'd like to see added to v1.0. 

I think it would also be nice to add, as part of this feature, tthe ability to also export the energies from a given simulation to a txt file.  Then, for testing this new feature, I would suggest have a test where the tool randomly generates site with an uncorrelated Gaussian DOS, exports the randomly generated energies to a file, and then imports the file again.  Various checks can be performed along the way to ensure that file export and import are working correctly and that the final energies imported match the original exported energies.

**Comment by JoshuaSBrown** [comment]
Ok, sounds like a plan.

**Comment by JoshuaSBrown** [comment]
Does this mean I'll merge with master or development? Are you going to add a second development for version 2.0?

**Comment by MikeHeiber** [comment]
You should create a feature branch from development.  Once finished, it will get merged back into development and then released with the next beta of v1.0.

**Comment by MikeHeiber** [comment]
The energies txt file should have the following format to parellel the morphology file:

Length, x-dimension (int)
Width, y-dimension (int)
Height, z-dimension (int)
energy for 0,0,0 (double)
energy for 0,0,1 (double)
.
.
.
energy for 0,0,Height-1 (double)
energy for 0,1,0 (double)
.
.
.
energy for 0,Width-1,Height-1 (double)
energy for 1,0,0 (double)
etc.

Let me know if this format is not clear.

Then, for writing and reading the file you can put your write/read commands in a series of nested loops:
for x
     for y
          for z

**Comment by JoshuaSBrown** [comment]
Just to be clear the inside of 40x60x80 file might look something like this:

```
40
60
80
-1.123
-1.235
-1.195
:
-1.183
```

**Comment by MikeHeiber** [comment]
Yes, and if they are all negative you could try storing positive numbers to reduce the filesize.

**Comment by JoshuaSBrown** [comment]
Can you remind me what the difference is between this and the morphology header? The morphology header has a few more lines in the header.

**Comment by MikeHeiber** [comment]
The morphology header also has information about things like domain size and blend ratio.

**Comment by JoshuaSBrown** [comment]
You don't actually read these lines in though. You just skip over them?

**Comment by MikeHeiber** [comment]
The lines are read when the file is imported into the Ising_OPV software tool, but for Excimontec those lines are skipped.

**Comment by JoshuaSBrown** [comment]
Joshua S Brown @JoshuaSBrown Jul 13 15:59
I also have questions related with how to deal with some of the other lattice values in the parmeter file. For instance the stdev values pop up the createCorrelatedDOS function and the Homo_donor and Lumo_donor etc show up in the calculateExcitonEvents function. Either we have to determine these values from the energies we are importing from the files, we need to disable to the functionality if importing or we different functionality to deal with this.

Michael C. Heiber @MikeHeiber Jul 13 20:08
I'll create the feature branch and implement the updates to the parameter file, then you can commit your changes to the init function and the other new functions for reading and writing the energy file.
when you import the energies from the file, you will not need to call the createCorrelatedDOS function
When you load energies in, I think you can just set the HOMO and LUMO values to zero.

Joshua S Brown @JoshuaSBrown Jul 15 23:19
So I'm fine with all these exceptions except with simply setting the Homo and Lumo values to 0, I think for this too be there needs to be a header in the energies.txt file indicating that it is associated with a neat polymer. This will give you flexibility in the future if you want to change it to a mixed system to simply change a keyword in the header. It also helps prevent users from assuming they can load any energies.

Michael C. Heiber @MikeHeiber 08:44
Currently site energies are defined as a sum of two quantities, the HOMO (or LUMO) and the disorder term. When importing energies from the file, the HOMO/LUMO energy can be set to 0, and the disorder term will have the imported energies.

Joshua S Brown @JoshuaSBrown 08:47
Ok, but I'm thinking it might be better to make the user put 0's for the Homo and Lumo value in the parameter.txt file so the user knows that these values are not being used. Or something of the sort.

Michael C. Heiber @MikeHeiber 08:50
But then the user has to set parameters that are not used in the simulation. When importing energies, all site energies are defined by the energies file and not by the parameter file
In the energies file, you do not need to specify the morphology because one can always associate separate morphology and energy files later if needed

Joshua S Brown @JoshuaSBrown 08:53
Ok, but is there a way to make it obvious to the user that those values are not being used when the energies are being read in?

Michael C. Heiber @MikeHeiber 08:53
we could add a note/comment in the parameter file

Joshua S Brown @JoshuaSBrown 08:55
Ok, what about the acceptor concentration, currently I throw an error if they have a acceptor concentration other than 0 when reading the site energies.

Michael C. Heiber @MikeHeiber 08:56
the energy file does not need to contain any morphology information
Just the dimensions and the energy values

Joshua S Brown @JoshuaSBrown 08:57
My point is that this is a little confusing. If I'm a user it will be hard for me to know what parameters are being used and which ones are not based on the settings.

Michael C. Heiber @MikeHeiber 08:58
Yes, I will add a note in the parameter file. Otherwise, we just need better user documentation/tutorials to explain how the parameters are being used.
I agree that there are a lot of parameters and options in there, and it's hard to figure out right away how each of them are being used.
And also which ones are being ignored

Joshua S Brown @JoshuaSBrown 09:01
What I have found useful is to set values that are not being used to a certain keyword, and throwing errors if the user has not defined them as such when they are not being used. This forces the user to know what is and isn't being used especially when you have 50+ parameters. But documentation of course is always helpful.

Michael C. Heiber @MikeHeiber 09:12
I also don't like forcing users to specifically disable lots of parameters. It's a tough decision.

Michael C. Heiber @MikeHeiber 09:21
I suggest to just start simple and get the basic features working, and then we can make things better/easier to use as we go.
We could spend months polishing each little part of the code and eventually have very few features and no science.

Joshua S Brown @JoshuaSBrown 09:22
That's a fair point.

Michael C. Heiber @MikeHeiber 09:23
It's good to brainstorm these ideas, but just do it quick and write an issue for later.
Then we can plan when to prioritize adding those things.

**Comment by JoshuaSBrown** [comment]
These issues are being addressed here:
https://github.com/MikeHeiber/Excimontec/tree/feature-site-energy-file-import-export

**Comment by MikeHeiber** [comment]
Resolved in #59
