### ISSUE TITLE
DOS and DOOS not correct? version v1.0.0-rc.2

### ISSUE THREAD

**Issue by ljakoster** [MikeHeiber/Excimontec#87]
In the steady-state transport test, the integral of the DOS and DOOS are not always correct (= equal to the total number of sites, resp. carriers in the simulation). When using the attached job and parameters, the integral over DOOS is correct (=1e19 cm-3), but the integral overt the DOS is too low by a factor of 1.1 (but I've seen larger deviations, up to 2). 
[4929459.zip](https://github.com/MikeHeiber/Excimontec/files/3028271/4929459.zip)

**Comment by MikeHeiber** [comment]
I have also reproduced this error with the standard testing parameters.  I will implement a fix as soon as possible and issue a new bugfix release. Thank you for identifying and reporting this error.

**Comment by MikeHeiber** [comment]
@ljakoster  This bug is now fixed in the master branch.

**Comment by ljakoster** [comment]
wow, that was quick. Thanks!
